import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import '../globals.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bit Txintxa | Exchange",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params
}: any) {

  const messages = await getMessages();


  return (
    <html
      lang={params.locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">

        <NextIntlClientProvider 
          locale={params.locale}
          messages={messages}
        >
          {children}
        </NextIntlClientProvider>
        
      </body>

    </html>
  );
}
